server {
       listen 8080;
       listen [::]:8080;
       add_header X-Frame-Options "SAMEORIGIN" always;
       add_header X-Content-Type-Options nosniff always;
       add_header Referrer-Policy 'origin' always;
       add_header Permissions-Policy "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()" always;
       add_header strict-transport-security "max-age=63072000; includeSubDomains; preload" always;


      server_name _;
      port_in_redirect off;
      error_page 404 /404.html;
      root /usr/share/nginx/html;
       index index.html;
       location / {
               try_files $uri $uri.html $uri/ $uri/index.html =404;
       }
}