import { USERTYPES } from '@/configs/app'
import { PERMISSIONS } from './permissions'

export const ROLE_POLICIES = {
  [USERTYPES.admin]: [
    PERMISSIONS.VIEW_HOME,

    // Orders
    PERMISSIONS.ORDER.VIEW,
    PERMISSIONS.ORDER.ADD,
    PERMISSIONS.ORDER.EDIT,
    PERMISSIONS.ORDER.DELETE,
    PERMISSIONS.ORDER.DETAIL,
    PERMISSIONS.ORDER.LIST,
    PERMISSIONS.ORDER.FOOTER_TOTAL,
    PERMISSIONS.ORDER.DELIVER_INFO,
    PERMISSIONS.ORDER.ORDER_DETAILS_PRICE,
    PERMISSIONS.ORDER.ORDER_DETAILS_TOTAL,
    PERMISSIONS.ORDER.TRACK_ORDER,
    PERMISSIONS.ORDER.VIEW_COUPON_INFO,

    // Products
    PERMISSIONS.PRODUCT.VIEW,
    PERMISSIONS.PRODUCT.LIST,
    // PERMISSIONS.PRODUCT.ADD,
    PERMISSIONS.PRODUCT.EDIT,
    PERMISSIONS.PRODUCT.DELETE,
    // PERMISSIONS.PRODUCT.BULK_UPLOAD_PRODUCTS,

    // Pharmacies
    PERMISSIONS.PHARMACY.VIEW,
    PERMISSIONS.PHARMACY.ADD,
    PERMISSIONS.PHARMACY.EDIT,
    PERMISSIONS.PHARMACY.LIST,
    PERMISSIONS.PHARMACY.CONNECT_ADYEN_ACCOUNT,

    // Pharmacy Admins
    PERMISSIONS.PHARMACY_ADMIN.VIEW,
    PERMISSIONS.PHARMACY_ADMIN.ADD,
    PERMISSIONS.PHARMACY_ADMIN.EDIT,
    PERMISSIONS.PHARMACY_ADMIN.LIST,
    PERMISSIONS.PHARMACY.FIELDS.EDIT_PRIORITY_RANKING,
    PERMISSIONS.PHARMACY.FIELDS.EDIT_COLLECT_POINT_ID,
    PERMISSIONS.PHARMACY.FIELDS.EDIT_COLLECT_POINT_NAME,
    PERMISSIONS.PHARMACY.SECTION.VIEW_FEES_AND_PRCIING,

    // COMMENTED - UBER_DIRECT
    // PERMISSIONS.PHARMACY.FIELDS.EDIT_EXPRESS_COST_STANDARD,
    // PERMISSIONS.PHARMACY.FIELDS.EDIT_SHOPPING_COST_STANDARD,
    PERMISSIONS.PHARMACY.EDIT_PHARMACY_ADMIN
  ],

  [USERTYPES.pharmacy_admin]: [
    // HOME
    PERMISSIONS.VIEW_HOME,

    // ORDERS
    PERMISSIONS.ORDER.VIEW,
    PERMISSIONS.ORDER.ADD,
    PERMISSIONS.ORDER.EDIT,
    PERMISSIONS.ORDER.DELETE,
    PERMISSIONS.ORDER.DETAIL,
    PERMISSIONS.ORDER.LIST,
    PERMISSIONS.ORDER.FOOTER_TOTAL,
    PERMISSIONS.ORDER.DELIVER_INFO,
    PERMISSIONS.ORDER.ORDER_DETAILS_PRICE,
    PERMISSIONS.ORDER.ORDER_DETAILS_TOTAL,
    PERMISSIONS.ORDER.TRACK_ORDER,

    // PRODUCTS
    PERMISSIONS.PRODUCT.VIEW,
    PERMISSIONS.PRODUCT.ADD,
    PERMISSIONS.PRODUCT.EDIT,
    PERMISSIONS.PRODUCT.DELETE,
    PERMISSIONS.PRODUCT.LIST,
    PERMISSIONS.PRODUCT.BULK_UPLOAD_PRODUCTS,
    PERMISSIONS.PRODUCT.VIEW_PRODUCT_ACTIONS,

    // PHARMCY
    PERMISSIONS.PHARMACY.VIEW,
    PERMISSIONS.PHARMACY.EDIT,
    PERMISSIONS.PHARMACY.LIST,
    PERMISSIONS.PHARMACY.CONNECT_ADYEN_ACCOUNT
  ],

  [USERTYPES.doctor]: [PERMISSIONS.VIEW_HOME, PERMISSIONS.ORDER.VIEW, PERMISSIONS.ORDER.LIST]
}
